### ISSUE TITLE
Program won't open past EULA

### ISSUE THREAD

**Issue by 7ylxr9** [PFCKrutonium/Windows-10-Login-Background-Changer#167]
I unzipped the download, double clicked the .exe, clicked Yes on the UAC, clicked Yes on the EULA, no window or icon on taskbar, nothing in task manager either.

**Comment by TheCypher1** [comment]
Do it again.

**Comment by 7ylxr9** [comment]
Still happening. Not quite sure what you thought would happen.

**Comment by TheCypher1** [comment]
It did the same to be, so I opened the file again and it worked the second time.

**Comment by SkullyKiddo** [comment]
Long-Horse please, go to the Event Viewer and check if there's any log. 
If you don't know how:
1 - Start > Run > "eventvwr"
2 - Windows Logs > Application
3 - Right Click on Application > "Clear Log..." > Clear
4 - Open the Windows-10-Login-Background-Changer and verify if anything is logged there (press f5 to refresh)

And post the log here.

**Comment by 7ylxr9** [comment]
Ok, there's an information log, application error and a .NET Runtime error.

Video going through the log since the following copy & paste may be incoherent: https://www.youtube.com/watch?v=tF7D_2h_w-I

**Information:**
_General:_
`Fault bucket 128887677730, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: W10 BG Logon Changer.exe
P2: 1.0.2.0
P3: 55c3b4a9
P4: Anonymously Hosted DynamicMethods Assembly
P5: 0.0.0.0
P6: 0
P7: 0
P8: ffffffff
P9: System.Windows.Markup.XamlParse
P10: 

Attached files:
C:\Users\Tyler\AppData\Local\Temp\WER8C2D.tmp.WERInternalMetadata.xml

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_W10 BG Logon Cha_ca543934c4148ef37aeabb2fecb9a9fc6514_09f47c18_65848df2

Analysis symbol: 
Rechecking for solution: 0
Report Id: fe04d1a5-26a7-4100-b974-f0142dadb7bf
Report Status: 0
Hashed bucket: 628685e193b55ff2e6db5e350b22f33f`

_Detail:_
` 128887677730 
   5 
   CLR20r3 
   Not available 
   0 
   W10 BG Logon Changer.exe 
   1.0.2.0 
   55c3b4a9 
   Anonymously Hosted DynamicMethods Assembly 
   0.0.0.0 
   0 
   0 
   ffffffff 
   System.Windows.Markup.XamlParse 

   C:\Users\Tyler\AppData\Local\Temp\WER8C2D.tmp.WERInternalMetadata.xml 
   C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_W10 BG Logon Cha_ca543934c4148ef37aeabb2fecb9a9fc6514_09f47c18_65848df2 

   0 
   fe04d1a5-26a7-4100-b974-f0142dadb7bf 
   0 
   628685e193b55ff2e6db5e350b22f33f`

**Application error:**
_General:_
`Faulting application name: W10 BG Logon Changer.exe, version: 1.0.2.0, time stamp: 0x55c3b4a9
Faulting module name: KERNELBASE.dll, version: 10.0.10240.16384, time stamp: 0x559f3b2a
Exception code: 0xe0434352
Fault offset: 0x000b3e28
Faulting process id: 0x642c
Faulting application start time: 0x01d0d60b6ed882b3
Faulting application path: C:\Users\Tyler\Desktop\Windows.10.Background.Changer\W10 BG Logon Changer.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report Id: fe04d1a5-26a7-4100-b974-f0142dadb7bf
Faulting package full name: 
Faulting package-relative application ID:`

_Detail:_
`W10 BG Logon Changer.exe 
   1.0.2.0 
   55c3b4a9 
   KERNELBASE.dll 
   10.0.10240.16384 
   559f3b2a 
   e0434352 
   000b3e28 
   642c 
   01d0d60b6ed882b3 
   C:\Users\Tyler\Desktop\Windows.10.Background.Changer\W10 BG Logon Changer.exe 
   C:\WINDOWS\SYSTEM32\KERNELBASE.dll 
   fe04d1a5-26a7-4100-b974-f0142dadb7bf`

**Runtime error:**
_General:_
`Application: W10 BG Logon Changer.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Windows.Markup.XamlParseException
Stack:
   at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri)
   at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext)
   at System.Windows.Application.LoadComponent(System.Uri, Boolean)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   at System.Windows.Application.RunDispatcher(System.Object)
   at System.Windows.Application.RunInternal(System.Windows.Window)
   at System.Windows.Application.Run(System.Windows.Window)
   at W10_Logon_BG_Changer.App.Main()`

_Detail:_
`Application: W10 BG Logon Changer.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.Windows.Markup.XamlParseException Stack: at System.Windows.Markup.WpfXamlLoader.Load(System.Xaml.XamlReader, System.Xaml.IXamlObjectWriterFactory, Boolean, System.Object, System.Xaml.XamlObjectWriterSettings, System.Uri) at System.Windows.Markup.WpfXamlLoader.LoadBaml(System.Xaml.XamlReader, Boolean, System.Object, System.Xaml.Permissions.XamlAccessLevel, System.Uri) at System.Windows.Markup.XamlReader.LoadBaml(System.IO.Stream, System.Windows.Markup.ParserContext, System.Object, Boolean) at System.Windows.Application.LoadBamlStreamWithSyncInfo(System.IO.Stream, System.Windows.Markup.ParserContext) at System.Windows.Application.LoadComponent(System.Uri, Boolean) at System.Windows.Application.DoStartup() at System.Windows.Application.<_ctor>b__0(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Windows.Threading.DispatcherOperation.Invoke() at System.Windows.Threading.Dispatcher.ProcessQueue() at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr) at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef) at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame) at System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame) at System.Windows.Application.RunDispatcher(System.Object) at System.Windows.Application.RunInternal(System.Windows.Window) at System.Windows.Application.Run(System.Windows.Window) at W10_Logon_BG_Changer.App.Main()`

**Comment by SkullyKiddo** [comment]
Ok, so... This exception makes no sense at all. This would happen due to a malformed XAML. Given the fact that many other people were able to open it, my guess is that the .exe is trying to bind to the wrong DLL.

It won't be possible to solve this or explore it further without logging these messages/exceptions (should be considered as a feature).

Long-Horse,

Could you please inform these two things:
- Have you executed it with administrative privileges?
- What device are you running this on?

If you can provide the installed programs it would be a good thing too. My guess is that there's a missing dll or its got an older version on your machine.

**Comment by 7ylxr9** [comment]
Yes, I am running with Admin privileges.

I am running on my custom built PC. Asrock Z87 Extreme4, Intel core i5 4430, 16 GB DDR3 RAM, GTX 660Ti, running Windows 10 Pro.

Installed programs list (just typing as I see it in control panel>uninstall a program):

1Password
7 Sticky Notes
Adobe After Effects
Adobe Creative Cloud
Adobe Flash Player 18 NPAPI
Adobe Illustrator
Adobe Media Encoder
Adobe Photoshop
Adobe Reader XI
Apple Application Support (32 & 64 bit)
Apple Mobile Device Support
Apple Software Update
ASIO4ALL
Audacity
AutoHotKey
BitTorrent
Bonjour
Bonjour Print Service
CCleaner
Counter Strike: Source
Ditto (copy paste manager)
Dropbox
Elgato Game Capture HD
f.lux
Game Captyre HD60
Garry's Mod
Google Chrome
HandBrake
Hexcells (steam game)
iCloud
IdleMaster (steam related)
Intel Smart Connect Technology (motherboard drivers)
Intel Driver Update Utility
iTunes
KMSpico (Sorry I stole MS Office I can only pay for it so many times)
LAME (audio codec thingy for Audacity)
Microsoft ASP .NET MVC 4 Runtime
MS Office 2013
*\* 10 different MS Visual C++ Redistributable*\* Vary between 2005-2013. Screenshot: https://i.imgur.com/F9UxFvM.png
MS Visual Studio 2010 Tools for Office Runtime
Minecraft
Mozilla Firefox
Mozilla Maintenance Service
Mp3Tag
Notepad++
Nvidia geforce experience, graphics driver and physx system software
Opera Beta
Origin (EA's Steam)
Pushbullet
Quicktime 7
Rainmeter
Razer Core
Razer Synapse
Realtek HD Audio Driver
Red Giant Link (After Effects plugin)
ShareX
Skype
Speccy
Spotify
Steam
Synergy
Teamviewer
Trapcode Suite (After Effects plugin)
Vegas Pro
VLC
WinDirStat
WinRAR
Wirecast (live streaming thing)

**Comment by SkullyKiddo** [comment]
Long-Horse, would you agree running a compiled version by me so you can check the log that it generates? I'm going to insert a few try/catches that will log the exception on text files as it goes.
Given the fact that you won't be able to see what's the code I'm placing here, is a trust based relation. If no, I'll ask you please to wait for the next version of the application. I'll be working on the log implementation for this PFCKrutonium\master version.

**Comment by SkullyKiddo** [comment]
Long-Horse, here's the compiled version with the correction: 
https://infotomb.com/5j4si

Here's the passed pull request:
https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/pull/194

If you choose to execute my compiled version, please open the log that will be generated locally and paste the content here. Thanks in advance.

**Comment by 7ylxr9** [comment]
I'm not at my PC right now. Where will the logs be stored and will it prompt an update when I open it or should I redownload it?

**Comment by SkullyKiddo** [comment]
You should download it again, because there's no update push. 
The log will be stored at the same folder of the application.
The download link is on the previous comment, but it's unofficial.

**Comment by darth62969** [comment]
@Long-Horse has your issue been solved with the new update?

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0

**Comment by 7ylxr9** [comment]
Nope, here's the log.

### W10_Logon_BG_Changer Crash

The invocation of the constructor on type 'W10_Logon_BG_Changer.MainWindow' that matches the specified binding constraints threw an exception.
'System.Dynamic.ExpandoObject' does not contain a definition for 'title_dg_disabled'
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<_ctor>b__0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

**Comment by monk45** [comment]
I get the same error with the same into in the log as Long-Horse.

**Comment by SkullyKiddo** [comment]
This is the commit that fixed this issue: https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/commit/68058bef1da08e4289348e3b649b0674011275be

**Comment by SkullyKiddo** [comment]
@Long-Horse and @monk45, please try the following as a workaround while the next version isn't released:
1 - Start > Run > "regedit"
2 - HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System
3 - Find/Create the value **DisableLogonBackgroundImage** (DWORD 32 bit)
4 - Set it to **0**
5 - Save and execute the application

It should work for now.

**Comment by monk45** [comment]
@SkullyKiddo Awesome, that did it for me. Thank you!

**Comment by SkullyKiddo** [comment]
To those who have the change privileges, this Issue has already been fixed and also has a workaround. It may be closed.

**Comment by osseigh** [comment]
It worked just after going through these steps 

> 1 - Start > Run > "regedit"
> 2 - HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System
> 3 - Find/Create the value DisableLogonBackgroundImage (DWORD 32 bit)
> 4 - Set it to 0
> 5 - Save and execute the application

I try an application that which altered my reg and after setting the (DWORD 32 bit)
to 0 the application started without any problem, thanks @SkullyKiddo
