### ISSUE TITLE
Crashing when selecting Background

### ISSUE THREAD

**Issue by ghost** [PFCKrutonium/Windows-10-Login-Background-Changer#271]
Hey! I previously changed the BG on a previous build of Windows. Now the changed BG is also on the new build. Now when I try to select the background I get this error: "There was an error while executing the application and it will be shutdown."
This is the log I get:
### W10_Logon_BG_Changer Crash

Not compatible with this PRI file.
   at SharedLibrary.LogonPriEditor.ModifyLogonGen2(String currentPri, String outputPri, String image)
   at W10_Logon_BG_Changer.Controls.BgEditorControl.SelectImageEvent_Clicked(Object sender, RoutedEventArgs e)
   at W10_Logon_BG_Changer.Controls.Commands.SelectImageCommand.Execute(Object parameter)
   at MahApps.Metro.Controls.TextBoxHelper.ButtonClicked(Object sender, RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

**Comment by darth62969** [comment]
Not compatible with this PRI file.

that is why what is your windows build number and what is the version of
the program you are using?

(: Jonathan :)

**Comment by Toyz** [comment]
it sounds like its trying to edit a already edited pri file instead of a orginal copy

**Comment by ghost** [comment]
@darth62969 I am using Windows 10 Build 10586.3 Version 1511
As for the program I am using v.1.2.0.0
Does this mean that 1.2.0.0 doesn't support this build?

@Toyz Yes I already have changed it on a previous build.

**Comment by darth62969** [comment]
i would recommend you download the default PRI and replace your PRI with that one and let us know if it solves your issue.

https://github.com/angelkyo/Windows-10-Login-Background-Changer/releases/download/zh_CN_1.1.0.0/Windows.UI.Logon.pri.bak.7z

**Comment by Toyz** [comment]
@BredzPro if the .bak you have is already edit the files will crash the editing as it's impossible rreedit a already edited file you need to have a clean orginal .bak

**Comment by BredzPro** [comment]
@darth62969 Thx. for your reply! I will try your solution as soon as I can. :)

**Comment by BredzPro** [comment]
@darth62969 Thanks! It worked! :smile:

**Comment by ghost** [comment]
@darth62969 Nope. Now it got worse. I can't even sign in. The lock screen shows only plain color.

**Comment by darth62969** [comment]
http://1drv.ms/1j6BlXG

that is my windows.ui.logon.pri.bak, download it then go to copy and paste it into you windows/systemresorces/windows.ui.logon directory then follow the instructions on how to revert your changes to that file.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login

written the tutorial

https://www.youtube.com/watch?v=J79ihzOKQLU

my video tutorial

**Comment by ghost** [comment]
@darth62969 I already formatted and reinstalled Windows 10. But, thanks for your help! :smile: 
Do you suggest using the software again as I am unsure now? >.<

**Comment by darth62969** [comment]
the software is and will always be "use at your own risk," we can not
guarantee it will always work or that nothing could screw it up. i would
suggest next time disabling any antivirus you may be running as we know
sometimes they interfere with the creation of the .bak file. which could
have been the root of your issue. it is up to you if you want to give it
another go or not.

(: Jonathan :)

**Comment by ghost** [comment]
@darth62969 okkay! ^.^
