### ISSUE TITLE
The UI doesn't want to start

### ISSUE THREAD

**Issue by RMFDEMON** [PFCKrutonium/Windows-10-Login-Background-Changer#278]
Hey, the UI doesn't want to start. It pops up with an error.
![screenshot 1](https://cloud.githubusercontent.com/assets/16737649/12374550/e554b1f6-bc5b-11e5-8605-8a429ea81698.png)

**Comment by RMFDEMON** [comment]
Here's a copy of the log file:

### W10_Logon_BG_Changer Crash

The invocation of the constructor on type 'W10_Logon_BG_Changer.MainWindow' that matches the specified binding constraints threw an exception.
'System.Dynamic.ExpandoObject' does not contain a definition for 'title_dg_disabled'
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

**Comment by emmatyping** [comment]
This is part of a typo in the code. Do you know how to build the project? If so, please grab the latest version and build. If not, let us know.

**Comment by RMFDEMON** [comment]
I don't, sorry.

**Comment by RMFDEMON** [comment]
Hey, did you guys fix the typo in the code?

**Comment by RMFDEMON** [comment]
And what language is it in, because if it's in java I can help.

**Comment by darth62969** [comment]
yes we did, its been fixed we just have not published a release yet

(: Jonathan :)

**Comment by RMFDEMON** [comment]
Hey Jonathan, when are you guys gonna publish?

**Comment by darth62969** [comment]
the worst answer... when we get around to it.

when i get back to my desktop i can do a release. really @pfckrutonium
would need to do it but he lost the digital signature, so right now it
doesn't really matter who does it.

still procrastinating....

(: Jonathan :)

**Comment by theminecoder** [comment]
Any luck on getting a release out to fix this?

Basically preventing use of the GUI on every machine I try it on :cry:

**Comment by darth62969** [comment]
fix the registry value, it is trying to pop up an error telling you to fix
that. i forget where exactly that is however... but it is the one that
disables the logon background.

(: Jonathan :)

**Comment by gabrielfsousa** [comment]
i have this problem too :(

**Comment by jj-obrien** [comment]
@darth62969 thanks for the hint!

This error occurs if you have edited the registry to remove the logon background Image entirely.
If the following key:
HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\System 
Has a 32-bit DWORD named DisableLogonBackgroundImage with value of 1 then removing that DWORD resolves the problem.

I guess a prompt to remove this value for you would be a nice fix for this issue in the app.

**Comment by emmatyping** [comment]
So I have made a new release, please try v 1.2.1
