### ISSUE TITLE
Doesnt work!

### ISSUE THREAD

**Issue by Sereniityy** [PFCKrutonium/Windows-10-Login-Background-Changer#284]
Everytime I choose an image to make my login screen, the app just gives me an error and shuts down.... HELP!

**Comment by Toyz** [comment]
What is the error? We kinda can't help without that error
On Feb 16, 2016 11:45 PM, Sereniityy notifications@github.com wrote:Everytime I choose an image to make my login screen, the app just gives me an error and shuts down.... HELP!

**Comment by Sereniityy** [comment]
It doesn't specifically tell me the error, all I do is choose a picture for
my login, then it says, There was an error executing the application and it
will be shut down?

**Comment by Toyz** [comment]
There should be a error log file that has the error that happened 
On Feb 17, 2016 5:31 PM, Sereniityy notifications@github.com wrote:It doesn't specifically tell me the error, all I do is choose a picture for
my login, then it says, There was an error executing the application and it
will be shut down?

**Comment by Sereniityy** [comment]
This is the error, but I don't know what it means...

### W10_Logon_BG_Changer Crash

Not compatible with this PRI file.
   at SharedLibrary.LogonPriEditor.ModifyLogonGen2(String currentPri,
String outputPri, String image)
   at
W10_Logon_BG_Changer.Controls.BgEditorControl.SelectImageEvent_Clicked(Object
sender, RoutedEventArgs e)
   at
W10_Logon_BG_Changer.Controls.Commands.SelectImageCommand.Execute(Object
parameter)
   at MahApps.Metro.Controls.TextBoxHelper.ButtonClicked(Object sender,
RoutedEventArgs e)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender,
RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at
System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs
e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender,
MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender,
RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender,
MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate
genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object
target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target,
RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source,
RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender,
RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean
trusted)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport
inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr
hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x,
Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr
hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd,
Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,
IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate
callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source,
Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority
priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr
wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame
frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

**Comment by emmatyping** [comment]
> Not compatible with this PRI file.

This means that the file storing the info we modify is incompatible, what build are you on? (see [here](http://www.windowscentral.com/how-check-your-windows-10-build) on how to check that)

**Comment by Sereniityy** [comment]
Ok, so here is the build.
Are you willing to update the program so I could use it for this build?I
would love it if you did. Thanks.
[image: Inline image 2]

**Comment by emmatyping** [comment]
Sorry, it seems the image is not loading, could you try posting a link? Or re-try uploading?

**Comment by Sereniityy** [comment]
The build is: 10586.104.

**Comment by Sereniityy** [comment]
Thats the best way I could tell you for now.

**Comment by emmatyping** [comment]
That's fine. Let me bring @Toyz back in on this one.

**Comment by Sereniityy** [comment]
Ok, thanks.

**Comment by Sereniityy** [comment]
Just asking out of curiosity, will doing this brick my PC?

**Comment by Sereniityy** [comment]
Hello?

**Comment by darth62969** [comment]
no it won't, i ran into a similar issue recently on one of my YouTube
videos. what you want to do is:
1. go download a clean PRI file, there should be a link on the main page of
   the repo.
2. go to windows/systemresources/windows.ui.logon
3. replace windows.ui.logon.pri with the clean PRI
4. delete the .bak file.

that should work, let me know if it does.

(: Jonathan :)

**Comment by Sereniityy** [comment]
Alright thanks a bunch!

**Comment by Sereniityy** [comment]
Im gonna try it out, and if it doesnt work, ill give you guys a shout.

**Comment by Sereniityy** [comment]
I tried the fix out, now I just have a frozen screen with my computer's
accent color.... What do I do now?

**Comment by Sereniityy** [comment]
I hope my PC isnt bricked...

**Comment by Sereniityy** [comment]
Well, I watched a video, dont need help. Thanks for all the help guys!

**Comment by fzls** [comment]
@Sereniityy well, i have a similar problem as you, i fixed it by entering advaced boot screen and choose to restore the system to last backup point(it only works if you have backed up before, good luck)

**Comment by Sereniityy** [comment]
Yeah, I'm restoring the PC, right now... I had a frozen black flickering
screen, and I put some commands in the advanced options category, and went
through a whole process of replacing .pri.bak files through Terminal, or
CMD. It didn't work so just going through a restore now, WELP.

**Comment by emmatyping** [comment]
Sorry to hear that @Sereniityy . Hope the restore is successful. You can leave another comment if you think you still have an issue, but I think since you seem to not need more help, I will close this. :)
