### ISSUE TITLE
Does not work with Version 1511 Build 10586

### ISSUE THREAD

**Issue by tjsreece** [PFCKrutonium/Windows-10-Login-Background-Changer#294]
## Issue

I ran the GUI version as an administrator, and included screenshots of both the OS version and the error messages that I received. The log file is also pasted at the bottom. I would include it as an attachment rather than a copy/paste but GitHub cant recognize txt files, even though they are on the acceptable uploads list. Reading the notice at the top of the project, I know that this program would more than likely not work with my build. This is just (hopefully) solid conformation and some insight.
Also the text should change from upgrade to **down**grade,  like so:

> Before using this application, please note that new insider preview builds (14279 or later) have rendered this program obsolete. Your best option at the moment is to simply wait, or _**downgrade**_ as part of the Insider Program.

Reading the original text, I assumed that if I was on Build 14279 I would need to upgrade to the latest build for the program to work. Or is there something I am missing here? I was never a part of the Insider Program. 
## Screenshots/Log file

![capture](https://cloud.githubusercontent.com/assets/7332551/14778649/f9740d28-0a88-11e6-8b77-c726d06bfb08.PNG)

![capture2](https://cloud.githubusercontent.com/assets/7332551/14778701/490e38a4-0a89-11e6-8f0f-6693fc501620.PNG)

```
### W10_Logon_BG_Changer Crash ###
The invocation of the constructor on type 'W10_Logon_BG_Changer.MainWindow' that matches the specified binding constraints threw an exception.
'System.Dynamic.ExpandoObject' does not contain a definition for 'title_dg_disabled'
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.LoadComponent(Uri resourceLocator, Boolean bSkipJournaledProperties)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at W10_Logon_BG_Changer.App.Main()

```

**Comment by emmatyping** [comment]
This is the same issue as #278 I will see if I can publish a release with the latest code soon. Definitely some time this week.
